<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>all</AnalysisMode>
		<CodeANalysosTreatWarningsAsErrors>true</CodeANalysosTreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>
</Project>